server:
  port: 8020
spring:
  application:
    name: consumer
eureka:
  instance:
    ip-address: 192.168.31.17
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
