server:
  port: 8011
spring:
  application:
    name: provider
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.31.17
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/